name: Release PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    env:
      HAS_PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN != '' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - run: python -m pip install -U pip
      - run: python -m pip install build twine
      - run: python -m build
      - run: python -m twine check dist/*.whl dist/*.tar.gz
      - name: Publish to PyPI with API token
        if: ${{ env.HAS_PYPI_API_TOKEN == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Publish to PyPI with trusted publishing
        if: ${{ env.HAS_PYPI_API_TOKEN != 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
